### ISSUE TITLE
Create a relational model diagram

### ISSUE THREAD

**Issue by michael-sevcik** [michael-sevcik/NPRG036-Data-Formats#92]

**Comment by patinoboh** [comment]
I have following suggestions for change : 
1. `Id` column in `Occupants` table **is** neccessary because othewise you couldn't have one person living in more houses due to the `personId` in `Occupants` being primary and foreign key
2. There is no need for `middleNames` column in `People` table [as I mentioned](https://github.com/michael-sevcik/NPRG036-Data-Formats/issues/94#issuecomment-1854340021)
3. There is a problem with town names. Which language tags should be required and which don't?
4. Same problem as 3 but with names of people.
5. Guys (@ori-no @rastoboh ) are very unhappy with ID's in all tables. They would prefer all of them to be in form `entityID`
5th point would require change in schema, as well as all .csv files
@michael-sevcik

**Comment by ori-no** [comment]
I agree with Patrik as these are the things we discussed at home while creating schema. However, I think point 5 does not need change. It does not have to be 1to1 correspondance with relation schema titles. It is more on what we three decide how to create the schema. What do you think about this @michael-sevcik. But in my opinion what should be discussed are the required columns which we do not have in many of our instances in data.ttl.

**Comment by michael-sevcik** [comment]
So I deleted the middleNames from people, which I had forgot to delete previously, I removed the required tag from names of streets and also from attributes colourHexCode and area from house.
![image](https://github.com/michael-sevcik/NPRG036-Data-Formats/assets/106611909/a717c006-3950-4e79-a060-8c66547fc43c)


> I have following suggestions for change :
> 
> 1. `Id` column in `Occupants` table **is** neccessary because othewise you couldn't have one person living in more houses due to the `personId` in `Occupants` being primary and foreign key

I believe this is exactly why we have the `LivesIn` table, because it specifies that a particular occupant lives in a specified house.

> 2. There is no need for `middleNames` column in `People` table [as I mentioned](https://github.com/michael-sevcik/NPRG036-Data-Formats/issues/94#issuecomment-1854340021)

true

> 3. There is a problem with town names. Which language tags should be required and which don't?

I removed it from both

> 4. Same problem as 3 but with names of people.

No names are required now, does it solve the issue? @patinoboh 

> 5. Guys (@ori-no @rastoboh ) are very unhappy with ID's in all tables. They would prefer all of them to be in form `entityID`
>    5th point would require change in schema, as well as all .csv files
>    @michael-sevcik

@patinoboh as @ori-no said it's not an issue, I left it untouched.

**Comment by patinoboh** [comment]
Ok thank you all. Only problem I can see now is lack of required parameters. I think it'll be fine tho, no need to change it now.

**Comment by patinoboh** [comment]
# We had to change the schema a little bit
Due to a problem in `metadata` file we needed to remove `ID` from `middleNames` table and make _primary key triplet_ of all other columns
TODO : 
- change the schema again please <3

**Comment by patinoboh** [comment]
[fixed](a7ecc04bca3f509c32e87fc57d3637e29a38fc51)
